/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.springframework.boot:spring-boot-starter-data-mongodb:3.1.5")
    api("org.springframework.boot:spring-boot-starter-web:3.1.5")
    api ("org.eu.acolyte:reactive-mongo_3:1.2.9")
    api ("org.springdoc:springdoc-openapi-ui:1.7.0")
    api ("org.mapstruct:mapstruct:1.6.0.Beta1")
    api ("org.mongodb:mongodb-driver-sync:4.9.1")
    runtimeOnly("org.springframework.boot:spring-boot-devtools:3.1.5")
    testImplementation("org.springframework.boot:spring-boot-starter-test:3.1.5")
    testImplementation ("org.junit.jupiter:junit-jupiter-api:5.8.1")
    testImplementation ("org.junit.jupiter:junit-jupiter-engine:5.8.1")
    testImplementation ("org.mockito:mockito-core:3.12.4")

}

group = "com.hypereon"
version = "0.0.1-SNAPSHOT"
description = "accountservice"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
